# ----------------------------------------------------------------
# SpeedrunRefactored Plugin Configuration
# ----------------------------------------------------------------

settings:
  # NORMAL or CASUAL - всі локації зі старту мають координати(і мають орієнтири). В Незері підсвічуються золоті блоки(в радіусі Х з конфіга).
  gamemode: "NORMAL" # Don't work now

  # The language file to use from the 'lang' folder (e.g., 'en', 'uk').
  language: "en"

  # Timer will start automatically when the first player joins the server.
  start-on-first-join: true

  # The ability to reassign the coordinates of any location using the command '/run new LOC_NAME'. If 'False', only works for 'Nether portal'.
  allow-reassigning-locations: true

  # Time in seconds to find the village before the task is removed. 600 = 10 minutes.
  village-search-timeout: 600

  # How to track player resources for tasks.
  # INVENTORY: Only counts items currently in players' inventories.
  # CUMULATIVE: Counts all items ever picked up or crafted by players during the run. (More demanding on the server)
  task-tracking-mode: "INVENTORY"

  # Dynamically scale required resource amounts based on the number of players online.
  scale-resources-by-playercount:
    enabled: true
    # Formula: base_amount * (1 + (player_count - 1) * multiplier)
    # A value of 0.5 means each additional player adds 50% of the base requirement.
    multiplier: 0.5
  # Log details of each speedrun attempt to 'logs/speedrun-log.txt'.
  log-attempts: true

  # NEW: Settings for the automatic structure scanner
  proximity-scanner:
    lava-pool:
      radius: 16
      required-source-blocks: 12
    village:
      radius: 32
    nether-portal:
      check-radius: 4
      search-radius: 90

# ----------------------------------------------------------------
# Task Progression
# Define the stages and the tasks within each stage.
# The plugin will progress from one stage to the next as all tasks are completed.
# ----------------------------------------------------------------
progression:
  # Stage 1: Basic setup
  1_GETTING_STARTED:
    world: "NORMAL" # Tasks are displayed when the player is in this world.
    tasks:
      # Use any log type as the key; the plugin aggregates all wood types. OAK_LOG is recommended.
      OAK_LOG: { amount: 16, display-name: "Wood", srbp: true}
      COBBLESTONE: { amount: 16, display-name: "Cobblestone", srbp: true}
  # Stage 2: Advancing to Iron Age
  2_IRON_AGE:
    world: "NORMAL"
    tasks:
      IRON_INGOT: { amount: 7, display-name: "Iron Ingots", srbp: false}
      # Use BREAD as a key for all cooked foods. The plugin will aggregate them.
      BREAD: { amount: 16, display-name: "Cooked Food", srbp: true}
  # Stage 3: Nether Exploration
  3_NETHER_EXPLORATION:
    world: "NETHER"
    tasks:
      ENDER_PEARL: { amount: 16, display-name: "Ender Pearls", srbp: false}
      BLAZE_ROD: { amount: 8, display-name: "Blaze Rods", srbp: false}

# ----------------------------------------------------------------
# Optional cosmetic rewards for completing tasks or stages.
# ----------------------------------------------------------------
rewards:
  enabled: true # Set to true to enable rewards
  # Command to run from the console when a single task is completed.
  # Use @p (closest player) or @a (all players) instead of %player% for console commands if specific player context isn't passed.
  on-task-complete:
    - "api:sound minecraft:entity.player.levelup 1.0 1.5"
    - "api:sound minecraft:item.totem.use 1.0 1.0"
    - "api:particle minecraft:totem_of_undying 30 0.5 0.5 0.5 0"
    - "api:particle minecraft:heart 10 0.2 0.2 0.2 0.1"

  on-stage-complete:
    - "tellraw @a [{\"text\":\"Stage Complete!\",\"color\":\"gold\",\"bold\":true}]"
    - "api:sound minecraft:block.end_portal.spawn 1.0 1.0"
    - "api:particle minecraft:spark 50 0.5 0.5 0.5 0.1"
    - "api:particle minecraft:flash 1 0 0 0 0"
    - "api:particle minecraft:explosion_emitter 1 0 0 0 0"
# ----------------------------------------------------------------
# Optional waypoints for navigating the world (no nether, no end).
# ----------------------------------------------------------------
structure_waypoints:
  enabled: true