name: Speedrun
version: '1.21.5-2.3.2'
main: org.speedrun.speedrun.Speedrun
api-version: '1.21'
author: 'deymon28'
description: A speedrun plugin with a timer, location tracking, and tasks.

commands:
  run:
    description: Main command for the Speedrun plugin.
    usage: /run <start|stop|reset|reload|skipstage|status|tasks|new|locate>
    aliases: [sr]
    permission: speedrun.player

permissions:
  speedrun.player:
    description: Allows using basic speedrun commands.
    default: true
  speedrun.admin:
    description: Allows using administrative speedrun commands.
    default: op
